### ISSUE TITLE
[Joss review] Installing groupyr installs unnecessary dependencies

### ISSUE THREAD

**Issue by janfreyberg** [richford/groupyr#39]
#### Describe the bug

Hi, as part of the JOSS review I'll open a few issues. If you'd prefer, I can compress them all into one issue instead.

#### Steps/Code to Reproduce

Installing the latest groupyr version on pypi also installs ipywidgets (and the large list of its dependencies). As far as I can tell, that's not required for the library (searching for `ipywidgets` in the source code doesn't yield any results.

#### Expected Results

Only dependencies required for groupyr functionality to be installed.

#### Versions

0.2.0

**Comment by richford** [comment]
Nice catch @janfreyberg. Resolved in #40. Thanks!
