### ISSUE TITLE
Extracting the regularisation path and coefficients along it

### ISSUE THREAD

**Issue by tim-oh** [richford/groupyr#57]
A neat feature of the LASSO and its software implementation is the ability to extract the regularisation path, including the coefficients along the way. It appears that sgl_path() offers such functionality, but it is either not exposed to the user or its usage is not described in the docs. Would it be possible to add an example of how to extract coefficients along the regularisation path?

**Comment by richford** [comment]
Hi @tim-oh, good suggestion. Thanks! I just added an autodoc example to the documentation in #58. Would you mind checking out the doc build from that pull request and providing some feedback?

To do so, you could [download these build artifacts](https://github.com/richford/groupyr/suites/3050721689/artifacts/69353954) and then view `index.html` in your web browser. I added one example and two functions to the API section.

**Comment by richford** [comment]
@tim-oh, I'm going to go ahead and merge the PR and close this issue (because I need some other changes published for use in a downstream library). If the new documentation is lacking, please feel free to reopen this issue.

**Comment by tim-oh** [comment]
Thanks for the swift response, that's fantastic!

Sorry for being slow on my side, couldn't work on it today. I'll try it out tomorrow and re-open if there's an issue.
