### ISSUE TITLE
Expose scoring to SGLCV and LogisticSGLCV

### ISSUE THREAD

**Issue by richford** [richford/groupyr#67]
#### Describe the workflow you want to enable

`sgl_scoring_path` and `logistic_sgl_scoring_path` have a `scoring` parameter to allow the user to specify an alternative scoring metric. But `SGLCV` and `LogisticSGLCV` do not expose this parameter to the user. We should fix that.

**Comment by richford** [comment]
Oh wait, this already exists for `LogisticSGLCV`, just not for `SGLCV`.

**Comment by arokem** [comment]
Is that documented somewhere?
