### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by JohannesWiesner** [richford/groupyr#78]
When using `groupyr.SGLCV` I get:

> /home/johannes.wiesner/.conda/envs/csp_wiesner_johannes/lib/python3.9/site-packages/copt/utils.py:41: DeprecationWarning:
> 
> Please use `MemoizeJac` from the `scipy.optimize` namespace, the `scipy.optimize.optimize` namespace is deprecated.

**Comment by arokem** [comment]
I think we're getting that from copt. See https://github.com/openopt/copt/pull/102 for a potential fix.

**Comment by richford** [comment]
I believe this issue as well is resolved in groupyr v0.3.2, which updated copt with @arokem's fix. Please do reopen if I'm mistaken.
