### ISSUE TITLE
Installing scikit-learn has changed: Has now to be scikit-learn, not sklearn

### ISSUE THREAD

**Issue by JohannesWiesner** [richford/groupyr#82]
Hi! Your package is part of a .yml file that I created to create a conda environment. I am not 100% sure but I think groupyr is responsible for the error I get:

![Screenshot_20230929_155025](https://github.com/richford/groupyr/assets/48254290/bf6413b5-281f-410a-b067-6ad3e0f84667)

Installing scikit-learn using pip has recently changed from `pip install sklearn` to `pip install scikit-learn`, so I think your requirements file has to be changed?

**Comment by richford** [comment]
Can you try updating groupyr to v0.3.2? That version uses the a more recent version of copt, which is the dependency that is causing your error.

**Comment by richford** [comment]
@JohannesWiesner , thanks for filing the issue. I'm going to close as completed under the assumption that a version bump will resolve. But please do reopen the issue if I'm mistaken.
